style(web): set theme of google button dark and add the button in loggin page
AlexGuillard/Area pull request #105
Opened 2024-01-03 11:21 UTC by Miou-zora

Linked to:
- close #85

2024-01-03 12:45 UTC, Benjicatch requested changes

2024-01-03 12:45 UTC, Benjicatch commented on web/src/Page/Login/login.tsx
> +        <GoogleButton />
only put it in the service view for now

2024-01-03 17:35 UTC, Benjicatch approved these changes

2024-01-05 09:33 UTC, AlexGuillard approved these changes
ok

2024-01-08 09:33 UTC, merged