feat(web): add icon to action / reaction
AlexGuillard/Area pull request #173
Opened 2024-01-11 15:18 UTC by Miou-zora

Linked to:
- close #125

2024-01-11 16:44 UTC, Pablodeibar approved these changes
:monkey:

2024-01-11 21:27 UTC, Benjicatch approved these changes

2024-01-12 10:31 UTC, AlexGuillard reviewed
isn't it dirty to put entire functions in the useeffect?

2024-01-12 10:33 UTC, Benjicatch requested changes

2024-01-12 10:33 UTC, Benjicatch commented on web/src/Component/Add/add.tsx
> +      axios.get(process.env.REACT_APP_SERVER_URL + "/" + storedToken + "/actions")
call storedToken in header

2024-01-12 10:33 UTC, Benjicatch commented on web/src/Component/Add/add.tsx
> +      axios.get(process.env.REACT_APP_SERVER_URL + "/" + storedToken + "/reactions")
call storedToken in header

2024-01-12 11:53 UTC, Miou-zora commented on web/src/Component/Add/add.tsx
> +      axios.get(process.env.REACT_APP_SERVER_URL + "/" + storedToken + "/reactions")
done

2024-01-12 11:53 UTC, Miou-zora commented on web/src/Component/Add/add.tsx
> +      axios.get(process.env.REACT_APP_SERVER_URL + "/" + storedToken + "/actions")
done

2024-01-12 11:54 UTC, Miou-zora commented
> isn't it dirty to put entire functions in the useeffect?

I think it's cleaner + it avoid to have some random shit warning + ratio

2024-01-12 12:26 UTC, Benjicatch approved these changes

2024-01-12 13:14 UTC, merged