feat(docker compose): dev and prod
AlexGuillard/Area pull request #69
Opened 2023-12-22 23:36 UTC by Miou-zora

Linked to:
- close #65

2023-12-22 23:37 UTC, Miou-zora commented
I've maybe fixed dependabot warnings

2023-12-26 11:36 UTC, Benjicatch requested changes

2023-12-26 11:36 UTC, Benjicatch commented on docker-compose.dev.yml
> +      # args:
to remove

2023-12-27 17:15 UTC, Miou-zora commented on docker-compose.dev.yml
> +      # args:
done

2023-12-27 17:16 UTC, Benjicatch approved these changes
ok

2023-12-27 17:17 UTC, Pablodeibar approved these changes
looks good

2023-12-27 17:37 UTC, Benjicatch approved these changes

2023-12-27 18:46 UTC, Pablodeibar approved these changes
good me too

2023-12-27 20:20 UTC, merged