feat(51 link loginregister mobile > main): add navigation between pages and edit and add component
AlexGuillard/Area pull request #88
Opened 2023-12-27 17:46 UTC by Kiya971

- Navigation between Login Page and Area Page
- Add Component
- Edit Component

2024-01-01 16:56 UTC, AlexGuillard requested changes
delete debug

2024-01-01 16:56 UTC, AlexGuillard commented on mobile/src/pages/Login.tsx
> +              console.log('pressed')
delete debug

2024-01-08 12:25 UTC, AlexGuillard submitted a review, later dismissed
ok

2024-01-08 16:05 UTC, Miou-zora approved these changes

2024-01-08 17:01 UTC, Benjicatch approved these changes
ok

2024-01-09 08:36 UTC, Pablodeibar approved these changes
ok

2024-01-09 12:52 UTC, merged